# Generated by Django 3.1.4 on 2020-12-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=50)),
                ('vehicle_manufacturer', models.CharField(max_length=50)),
                ('vehicle_year', models.IntegerField()),
                ('vehicle_battery_size', models.IntegerField()),
                ('vehicle_WLTP_range', models.IntegerField()),
                ('vehicle_cost', models.IntegerField()),
                ('vehicle_power', models.IntegerField()),
            ],
        ),
    ]
